name: Build and Deploy
on:
  push: 
    branches: [master]

jobs: 
  build: 
    name: build
    runs-on: ubuntu-latest
    steps: 
      - name: npm Install
        run: npm install
      - name : Build Site
        run: npm run build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: upload to godaddy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with: 
          server: ftp.xenonads.com
          username: github@toufic.me
          password: ${{ secrets.ftp_password }}
